/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ActorControl;
import Modelo.Actor;
import javax.swing.table.DefaultTableModel;
import Controlador.PeliculaControl;
import Controlador.PersonajeControl;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author paulp
 */
public class ActVentana extends javax.swing.JInternalFrame {

    private ActorControl actorCtrl;
    private PersonajeControl personajeControl;
    private PeliculaControl peliculaControl;
    
    public ActVentana() {
        initComponents();
        actorCtrl = new ActorControl();
        personajeControl = new PersonajeControl();
        peliculaControl = new PeliculaControl();
        this.cargarActorTabla();
    }

    public void cargarActorTabla() {
        DefaultTableModel modelo = (DefaultTableModel) TablaActor.getModel();
        modelo.setRowCount(0);
        for (Actor actor : actorCtrl.listar()) {
            Object[] rowData = {actor.getNombre(),
                actor.getNacionalidad(),
                actor.getFechanacimiento(),
                actor.getEdad(),
                actor.getPelicula().getNombre(),
                actor.getPersonaje().getNombrePer(),};
            modelo.addRow(rowData);
        }
        TablaActor.setModel(modelo);
    }

    public JButton getBtncrear() {
        return btncrear;
    }

    public JButton getBtneliminar() {
        return btneliminar;
    }

    public JButton getBtnlistar() {
        return btnlistar;
    }

    public JButton getBtnmodificar() {
        return btnmodificar;
    }

//    public JTable getTablaActor() {
//        return TablaActor;
//    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaActor = new javax.swing.JTable();
        txtnacionalidad = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        btncrear = new javax.swing.JButton();
        btnlistar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("ACTOR/ACTRIZ");

        TablaActor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NOMBRE ", "NACIONALIDAD", "FECHA NACI", "EDAD", "PELICULA", "PERSONAJE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaActor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaActorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaActor);

        btncrear.setText("CREAR");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btnlistar.setText("LISTAR");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("NACIONALIDAD:");

        jLabel4.setText("FECHA NACIMIENTO:");

        jLabel5.setText("EDAD:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtedad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtfecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(190, 190, 190))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(7, 7, 7))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btncrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlistar)
                .addGap(79, 79, 79)
                .addComponent(btnmodificar)
                .addGap(38, 38, 38)
                .addComponent(btneliminar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear)
                    .addComponent(btnlistar)
                    .addComponent(btnmodificar)
                    .addComponent(btneliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaActorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaActorMouseClicked
        // TODO add your handling code here:
        int fila = TablaActor.getSelectedRow();
        String nombre = TablaActor.getValueAt(fila, 0).toString();
        String nacionalidad = TablaActor.getValueAt(fila, 1).toString();
        int fecha = (int) TablaActor.getValueAt(fila, 2);
        int edad = (int) TablaActor.getValueAt(fila, 3);

       // btncrear.setEnabled(false);
        txtnombre.setEnabled(false);
        txtnombre.setText(nombre);
        txtnacionalidad.setText(nacionalidad);
        txtfecha.setText(String.valueOf(fecha));
        txtedad.setText(String.valueOf(edad));
    }//GEN-LAST:event_TablaActorMouseClicked

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        String nombre = txtnombre.getText();
        String nacionalidad = txtnacionalidad.getText();

        int fecha = Integer.parseInt(txtfecha.getText());
        int edad = Integer.parseInt(txtedad.getText());

        Actor actor = new Actor(nombre, nacionalidad, fecha, edad);

        System.out.println(personajeControl.buscar(nombre));
        System.out.println(peliculaControl.buscar(nombre));

        if (!nombre.isBlank() && !nacionalidad.isBlank() && !txtfecha.getText().isBlank() && !txtedad.getText().isBlank()) {

            if (!personajeControl.buscar(nombre).equals(null) && !peliculaControl.buscar(nombre).equals(null)) {
                String[] params = new String[2];
                params[0] = nombre;
                params[1] = nacionalidad;

                actorCtrl.crear(params, fecha, edad,personajeControl.buscar(nombre),peliculaControl.buscar(nombre));
            }
        }

        txtnombre.setText("");
        txtnacionalidad.setText("");
        txtfecha.setText("");
        txtedad.setText("");
    }//GEN-LAST:event_btncrearActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        String nombre = txtnombre.getText();
        String nacionalidad = txtnacionalidad.getText();
        int fecha = 0;
        int edad = 0;

        try {
            fecha = Integer.parseInt(txtfecha.getText());
            edad = Integer.parseInt(txtedad.getText());
        } catch (Exception e) {
            System.out.println(e);
        }

        Actor actor = new Actor(nombre, nacionalidad, fecha, edad);

        if (!nombre.isBlank() && !nacionalidad.isBlank() && !txtfecha.getText().isBlank() && !txtedad.getText().isBlank()) {
            if (!personajeControl.buscar(nombre).equals(null) && !peliculaControl.buscar(nombre).equals(null)) {
                String[] params = new String[2];
                params[0] = nombre;
                params[1] = nacionalidad;

                actorCtrl.crear(params, fecha, edad,personajeControl.buscar(nombre),peliculaControl.buscar(nombre));
            }
        }
        cargarActorTabla();
        txtnombre.setText("");
        txtnacionalidad.setText("");
        txtfecha.setText("");
        txtedad.setText("");
        
        JOptionPane.showMessageDialog(null, "Datos Ingresados Correctamente");
    }//GEN-LAST:event_btnlistarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        String nombre = txtnombre.getText();
        String nacionalidad = txtnacionalidad.getText();

        int fecha = Integer.parseInt(txtfecha.getText());
        int edad = Integer.parseInt(txtedad.getText());

        Actor actor = new Actor(nombre, nacionalidad, fecha, edad);

        if (!nombre.isBlank() && !nacionalidad.isBlank() && !txtfecha.getText().isBlank() && !txtedad.getText().isBlank()) {
            String[] params = new String[2];
            params[0] = nombre;
            params[1] = nacionalidad;

            actorCtrl.modificar(params, fecha, edad,personajeControl.buscar(nombre),peliculaControl.buscar(nombre));
        }
        cargarActorTabla();

        txtnombre.setEnabled(true);
        txtnombre.setText("");
        txtnacionalidad.setText("");
        txtfecha.setText("");
        txtedad.setText("");
        
        JOptionPane.showMessageDialog(null, "Datos Modificados Correctamente");
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        String nombre = txtnombre.getText();
        actorCtrl.eliminar(nombre);
        cargarActorTabla();
        
        txtnombre.setEnabled(true);
        txtnombre.setText("");
        txtnacionalidad.setText("");
        txtfecha.setText("");
        txtedad.setText("");
        
        JOptionPane.showMessageDialog(null, "Datos Eliminados Correctamente");
    }//GEN-LAST:event_btneliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaActor;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlistar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtnacionalidad;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
