/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Modelo.Actor;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulp
 */
public class Principal extends javax.swing.JFrame {

    private ActVentana v1;
    private PerVentana v2;
    private PeliVentana v3;
        
  
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        v1 = new ActVentana();
        v2 = new PerVentana();
        v3 = new PeliVentana();

    }

//    public void cargarActorTabla(JTable TablaActorp) {
//        DefaultTableModel modelo = (DefaultTableModel) TablaActorp.getModel();
//        modelo.setRowCount(0);
//        for (Actor actor : actorCtrl.listar()) {
//            Object[] rowData = {actor.getNombre(),
//                actor.getNacionalidad(),
//                actor.getFechanacimiento(),
//                actor.getEdad(),
//                actor.getPelicula().getNombre(),
//                actor.getPersonaje().getNombrePer(),};
//            modelo.addRow(rowData);
//        }
//        TablaActorp.setModel(modelo);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPersonaje = new javax.swing.JMenu();
        menuCrearPersonaje = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuCrearPelicula = new javax.swing.JMenuItem();
        menuActor = new javax.swing.JMenu();
        menuCrearActor = new javax.swing.JMenuItem();
        menuModActor = new javax.swing.JMenuItem();
        menuElimActor = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        menuPersonaje.setText("Personaje");

        menuCrearPersonaje.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuCrearPersonaje.setText("Crear Personaje");
        menuCrearPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearPersonajeActionPerformed(evt);
            }
        });
        menuPersonaje.add(menuCrearPersonaje);

        jMenuBar1.add(menuPersonaje);

        jMenu1.setText("Pelicula");

        menuCrearPelicula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuCrearPelicula.setText("Crear Pelicula");
        menuCrearPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearPeliculaActionPerformed(evt);
            }
        });
        jMenu1.add(menuCrearPelicula);

        jMenuBar1.add(jMenu1);

        menuActor.setText("Actor");

        menuCrearActor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuCrearActor.setText("Crea Actor");
        menuCrearActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearActorActionPerformed(evt);
            }
        });
        menuActor.add(menuCrearActor);

        menuModActor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuModActor.setText("Modificar Actor");
        menuModActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModActorActionPerformed(evt);
            }
        });
        menuActor.add(menuModActor);

        menuElimActor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuElimActor.setText("Eliminar Actor");
        menuElimActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuElimActorActionPerformed(evt);
            }
        });
        menuActor.add(menuElimActor);

        jMenuBar1.add(menuActor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCrearActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearActorActionPerformed
        escritorio.add(v1);
        v1.setVisible(true);
        v1.getBtncrear().setEnabled(true);
        v1.getBtnlistar().setEnabled(true);
        v1.getBtneliminar().setEnabled(false);
        v1.getBtnmodificar().setEnabled(false);
    }//GEN-LAST:event_menuCrearActorActionPerformed

    private void menuCrearPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearPersonajeActionPerformed
        escritorio.add(v2);
        v2.setVisible(true);
    }//GEN-LAST:event_menuCrearPersonajeActionPerformed

    private void menuCrearPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearPeliculaActionPerformed
        escritorio.add(v3);
        v3.setVisible(true);    
    }//GEN-LAST:event_menuCrearPeliculaActionPerformed

    private void menuModActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModActorActionPerformed
        escritorio.add(v1);
        v1.setVisible(true);
        v1.getBtneliminar().setEnabled(false);
        v1.getBtncrear().setEnabled(false);
        v1.getBtnlistar().setEnabled(false);
        v1.getBtnmodificar().setEnabled(true);
        //cargarActorTabla(v1.getTablaActor());
    }//GEN-LAST:event_menuModActorActionPerformed

    private void menuElimActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuElimActorActionPerformed
        escritorio.add(v1);
        v1.setVisible(true);
        v1.getBtnmodificar().setEnabled(false);
        v1.getBtncrear().setEnabled(false);
        v1.getBtnlistar().setEnabled(false);
        v1.getBtneliminar().setEnabled(true);
    }//GEN-LAST:event_menuElimActorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu menuActor;
    private javax.swing.JMenuItem menuCrearActor;
    private javax.swing.JMenuItem menuCrearPelicula;
    private javax.swing.JMenuItem menuCrearPersonaje;
    private javax.swing.JMenuItem menuElimActor;
    private javax.swing.JMenuItem menuModActor;
    private javax.swing.JMenu menuPersonaje;
    // End of variables declaration//GEN-END:variables
}
